spring.application.name=utility-billing-system
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/utility_billing
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

app.jwt.secret=Zrjv9gYwM8m2z6zL0i8wZzN5rX9Y3qYhP8Y4w8r3X2I=
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jolieprincesseishimwe@gmail.com
spring.mail.password=tcrukzzqmsvlkhzx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=jolieprincesseishimwe@gmail.com
app.mail.from-name=Utility Billing System

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
logging.level.org.springframework.security=INFO
logging.level.com.utility.billing=DEBUG
