package com.utility.billing.controller;

import com.utility.billing.dto.NotificationResponse;
import com.utility.billing.enums.Role;
import com.utility.billing.exception.ResourceNotFoundException;
import com.utility.billing.exception.UnauthorizedException;
import com.utility.billing.repository.CustomerRepository;
import com.utility.billing.service.NotificationService;
import com.utility.billing.util.SecurityUtils;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/notifications")
@RequiredArgsConstructor
@Tag(name = "9. Notifications", description = "View and manage customer notification messages generated by billing and payment events.")
public class NotificationController {
    private final NotificationService notificationService;
    private final CustomerRepository customerRepository;

    @GetMapping("/customer/{customerId}")
    @PreAuthorize("hasAnyRole('ADMIN','FINANCE','CUSTOMER')")
    @Operation(summary = "List customer notifications", description = "Returns notification messages for a customer. Customer users can only access their own notifications.")
    public List<NotificationResponse> findByCustomer(@PathVariable Long customerId) {
        ensureOwnCustomerIfCustomer(customerId);
        return notificationService.findByCustomer(customerId);
    }

    @PatchMapping("/{id}/read")
    @PreAuthorize("hasAnyRole('ADMIN','FINANCE','CUSTOMER')")
    @Operation(summary = "Mark notification as read", description = "Marks one notification as read. Customer users can only update their own notifications.")
    public NotificationResponse markRead(@PathVariable Long id) {
        return notificationService.markRead(id);
    }

    private void ensureOwnCustomerIfCustomer(Long customerId) {
        var user = SecurityUtils.currentUser();
        if (user.getRole() == Role.ROLE_CUSTOMER) {
            var customer = customerRepository.findById(customerId).orElseThrow(() -> new ResourceNotFoundException("Customer not found"));
            if (!customer.getEmail().equalsIgnoreCase(user.getEmail())) {
                throw new UnauthorizedException("Customers can only access their own notifications");
            }
        }
    }
}
